### ISSUE TITLE
0.3.1.6 Worse Performance than 0.3.1.4

### ISSUE THREAD

**Issue by CriticalComposer** [Nielk1/VSCView#12] opened 2019-05-20 14:26 UTC
0.3.1.6 came with some nice QoL features and a huge fix for the gyro reading but I'm getting some poor performance with it. My two concerns are the visuals for moving across the pad and the CPU usage. The pad trails aren't as smooth as they used to be and they seem to be updated less frequently then before. This causes circular motions to have edges and the movement as a whole appears laggy, for lack of a better word. Somehow, though, this version also uses a lot more resources. At idle it has 2-3x more CPU usage and when both pads are in use it reaches as much as 4x as much; the largest difference I've seen was an extra 10% CPU usage. For reference, I am using a 2012 i5-3570K (3.4GHz quad-core). 

[Here is a visual aid](https://www.youtube.com/watch?v=ZH1h8AxSaco) to help describe my issues.

**Comment by Nielk1** [comment] 2019-05-20 17:37
Hmm, that's interesting.  Two major changes occurred that are having opposite effects:

1. The paint system was decoupled providing far better CPU use (lower) during activity.
2. The paint system was given a high performance "timer" that ensures it runs at an even frame rate, though this frame rate could be slower than how it was running before.

I suspect that while the cost of rendering is lower now, the fixed frame rate rendering is causing an increase in cost.  My ideas for this situation:

- Ensure rendering is prevented if there is no new activity to draw.  This can be done by allowing all OSD elements to indicate if they are "dirty" and if none are dirty, do not draw a frame.  This could have side effects so it would probably do best if done as an option.
- Regional Redraws, that is detecting "dirty zones" and only redrawing those areas.
- Remove hard coded FPS and add it as an option the user can edit.

I could be wrong about what the problem is, but it makes the most sense.

**Comment by Nielk1** [comment] 2019-05-20 20:56
@WombatFromHell Any thoughts on this?  I've locally created a dirty check that prevents a paint if the frame will be the same and even tried doing OSD data updates (not to be confused with render updates) on a different timer/thread.  On my personal machine no matter what I do the CPU goes from 0-1% on 1.3.4 to 1% on 1.3.6 to 1-2% on my test builds.  I also notice that no matter what I do the pad trails are more jagged then they used to be.  What's odd is their fade time is the same, which means that all methods are treating the heat history list the same, so my best guess is that the old code's unreliable timer resulted in a more irregular placement of points that caused a smoother looking line.

**Comment by WombatFromHell** [comment] 2019-05-20 22:46
I did a fair amount of profiling during development to try to find the root cause of this issue. It kept leading me back to the `OnPaint` handler chain. Take a look at this profiler output (after using both Pads for a few seconds) as an example of what I mean:

![Annotation 2019-05-20 162109](https://user-images.githubusercontent.com/1840075/58055625-91164500-7b1b-11e9-9870-391dc735b8c9.jpg)

You'll notice that calls to `OnPaint()` and `DrawImage()` take up the overwhelming majority of CPU usage compared to everything else the app is doing. I suspect the reason for this is how `OnPaint` works in Windows Forms: it can be called multiple times for a single invalidated region causing a stack of calls that pile up on the event loop and hinder the app's rendering performance. This is made even worse by the fact that some image processing is still being done inside the `OnPaint` chain (despite the use of a memoized `ImageCache`).

I'm no expert when it comes to this sort of stuff, but a few suggestions come to mind on what can be done to help with this issue:

* More or all of the processing needs to be moved out into another thread (better still, into a threaded producer) so that `OnPaint` simply takes the current state from the threaded cache and renders it with `DrawImage()`.
* Implementation of region invalidation would help reduce full redraws (less pixels pushed to `DrawImage()` reduces CPU usage and also reduces subsequent calls to `OnPaint`).

**Comment by CriticalComposer** [comment] 2019-05-21 17:20
I tried out the PR13 test build and it is a vast improvement over v0.3.1.6. It is such an improvement that I ran it against v0.3.1.4 and couldn't tell the two versions apart. CPU usage has also dropped and is more in line with 0.3.1.4, sometimes it's even lower.

**Comment by WombatFromHell** [comment] 2019-05-21 17:32
I guess I owe an apology. The rendering chain is still partially responsible for some of the unnecessary CPU usage, but the busy-wait loop I was using was wasting an unnecessary amount of time polling and waiting for a rendering window to come up. Using a threaded timer is more efficient, even though it's less accurate, because all timers in .NET are kernel timers and are updated all at once.

I'll investigate to see if there's something more that can be done about performance in the rendering chain. I was thinking of some experiments with a threaded rendering cache to replace the existing image processing that's currently being done during `OnPaint`.

**Comment by Nielk1** [comment] 2019-06-11 06:23
This is resolved by v0.3.1.7, thanks again WombatFromHell for your help on rendering performance and CPU use.

**Closed by Nielk1** 2019-06-11 06:23 UTC
